services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on localhost:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME} # Default admin username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD} # Default admin password
      MONGO_INITDB_DATABASE: app # Default database name
    volumes:
      - mongodb_data:/data/db # Persist data in a Docker volume
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js # Mount the initialization script

  mongo-express:
    image: mongo-express:1.0
    container_name: mongo-express
    ports:
      - "8081:8081" # Expose Mongo Express on localhost:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME} # Admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD} # Admin password
      ME_CONFIG_MONGODB_SERVER: mongodb # MongoDB service name in the network
    depends_on:
      - mongodb # Ensure MongoDB starts before Mongo Express

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000" # Expose FastAPI server on localhost:8000
    depends_on:
      - mongodb # Ensure MongoDB starts before the backend
    environment:
      MONGO_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/app # MongoDB connection URL

volumes:
  mongodb_data:
